name: build

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build from"
        required: true
        type: string
        default: "master"

env:
  GIT_BRANCH: "${{ inputs.branch || github.ref_name }}"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout VSCodeVim
        uses: actions/checkout@v3
        with:
          ref: "${{ env.GIT_BRANCH }}"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Prettier
        if: matrix.os != 'windows-latest'
        run: yarn prettier:check

      - name: Lint
        run: yarn lint

      - name: Build
        run: gulp webpack

      - name: Test on ubuntu-latest
        if: matrix.os != 'windows-latest'
        run: |
          gulp prepare-test
          xvfb-run -a yarn test

      - name: Test on windows-latest
        if: matrix.os == 'windows-latest'
        run: |
          gulp prepare-test
          yarn test

      - name: Build extension package
        id: build_vsix
        run: |
          yarn package

      - name: Upload the VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: vscode-extension-${matrix.os}
          path: "*.vsix"
